sudo: required
dist: trusty
before_install:
- "sudo apt-get update && sudo apt-get install asymptote biber latexmk texlive-full"
script:
- cd book
- latexmk --latexoption=-interaction=nonstopmode -halt-on-error --pdf calcnotes
deploy:
  provider: releases
  file:
  - book/calcnotes.pdf
  skip_cleanup: true
  on:
    tags: true
